version: '3'

services:
  backend:
    build: ./backend
    container_name: backend_container
    image: lfernando2024/backend:latest
    ports:
      - '5000:5000'
    volumes:
      - /backend:/project
  frontend:
    build: ./frontend
    container_name: frontend_container
    image: lfernando2024/frontend:latest
    ports:
      - '3000:3000'
    volumes:
      - /frontend:/node_modules
      - /frontend:/src