"""empty message

Revision ID: 0f1cb1569030
Revises: 61f71990923e
Create Date: 2024-03-03 00:39:56.257786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f1cb1569030'
down_revision = '61f71990923e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_approver_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('users_requester_id_fkey', type_='foreignkey')
        batch_op.drop_column('requester_id')
        batch_op.drop_column('approver_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approver_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('requester_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_requester_id_fkey', 'users', ['requester_id'], ['user_id'])
        batch_op.create_foreign_key('users_approver_id_fkey', 'users', ['approver_id'], ['user_id'])

    # ### end Alembic commands ###
