"""userPosition5

Revision ID: 128bb4d43cd2
Revises: 69a979644c67
Create Date: 2024-09-30 14:27:54.041223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128bb4d43cd2'
down_revision = '69a979644c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('employee_position',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'positions', ['employee_position'], ['position_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('employee_position',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
