"""empty message

Revision ID: 21893d5759f3
Revises: 0f1cb1569030
Create Date: 2024-03-03 00:40:51.167457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21893d5759f3'
down_revision = '0f1cb1569030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requester_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('approver_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['requester_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'users', ['approver_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('approver_id')
        batch_op.drop_column('requester_id')

    # ### end Alembic commands ###
