"""Some content

Revision ID: 368a3e0c2a85
Revises: 313ce185511c
Create Date: 2024-11-04 23:39:27.363575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368a3e0c2a85'
down_revision = '313ce185511c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_name', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_column('short_name')

    # ### end Alembic commands ###
