"""Initial Migration

Revision ID: 4295f82c8435
Revises: 
Create Date: 2024-01-10 13:18:10.413265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4295f82c8435'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('user_groups', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('operating_system', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('server_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('employee_code', sa.String(length=20), nullable=True),
    sa.Column('role_in_application', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('access',
    sa.Column('access_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_groups', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.server_id'], ),
    sa.PrimaryKeyConstraint('access_id')
    )
    op.create_table('group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server.server_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('notification',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_access', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_access'], ['access.access_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('group')
    op.drop_table('access')
    op.drop_table('users')
    op.drop_table('server')
    # ### end Alembic commands ###
