"""Access request requester_id

Revision ID: 4ff5f02f24ac
Revises: 128bb4d43cd2
Create Date: 2024-10-01 01:04:45.631253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff5f02f24ac'
down_revision = '128bb4d43cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requester_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['requester_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('requester_id')

    # ### end Alembic commands ###
