"""userPosition4

Revision ID: 69a979644c67
Revises: b0aa07083856
Create Date: 2024-09-30 14:23:22.269121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69a979644c67'
down_revision = 'b0aa07083856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('employee_position',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('employee_position',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
