"""Some content

Revision ID: 77a2be73425f
Revises: 
Create Date: 2024-09-21 19:45:15.947545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77a2be73425f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commands',
    sa.Column('command_id', sa.Integer(), nullable=False),
    sa.Column('comando', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('command_id')
    )
    op.add_column('servers', sa.Column('hostname', sa.String(length=255), nullable=False))
    op.add_column('servers', sa.Column('pkey', sa.String(length=255), nullable=False))
    op.drop_column('servers', 'user_groups')
    op.drop_column('servers', 'password')
    op.drop_column('servers', 'port')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('servers', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('servers', sa.Column('user_groups', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('servers', 'pkey')
    op.drop_column('servers', 'hostname')
    op.drop_table('commands')
    # ### end Alembic commands ###
