"""AccessRequest3

Revision ID: a58eeaf6f8d5
Revises: d55ce76eddaf
Create Date: 2024-09-30 13:54:42.259017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58eeaf6f8d5'
down_revision = 'd55ce76eddaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'access', ['access_id'], ['access_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('access_id')

    # ### end Alembic commands ###
