"""empty message

Revision ID: aa311edfdad6
Revises: c21fa7f1c822
Create Date: 2024-03-03 00:22:00.674744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa311edfdad6'
down_revision = 'c21fa7f1c822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_role_in_application_fkey', type_='foreignkey')
        batch_op.drop_column('role_in_application')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_in_application', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('users_role_in_application_fkey', 'roles', ['role_in_application'], ['role_id'])

    # ### end Alembic commands ###
