"""Some content

Revision ID: b52e74d1cbaa
Revises: 368a3e0c2a85
Create Date: 2024-11-04 23:53:58.915744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52e74d1cbaa'
down_revision = '368a3e0c2a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_requests', schema=None) as batch_op:
        batch_op.alter_column('access_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_requests', schema=None) as batch_op:
        batch_op.alter_column('access_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
