"""Access request requester_id5

Revision ID: ce66949f6838
Revises: 4e24584965f4
Create Date: 2024-10-01 09:15:33.588120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce66949f6838'
down_revision = '4e24584965f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
